import VerifyForm from '@/components/VerifyForm'
import { FiShield, FiCheckCircle, FiAlertTriangle, FiInfo } from 'react-icons/fi'

export default function VerifyPage() {
    return (
        <div className="section">
            <div className="container max-w-3xl">
                <div className="text-center mb-12">
                    <div className="w-14 h-14 bg-accent/10 rounded-full flex items-center justify-center mx-auto mb-4">
                        <FiShield className="w-7 h-7 text-accent" />
                    </div>
                    <h1 className="text-h2 text-white mb-4">Verify Randomness</h1>
                    <p className="text-gray-400 max-w-xl mx-auto">
                        Enter a token request ID to verify its on-chain randomness seed.
                        Prove that the randomness was generated fairly by ICP.
                    </p>
                </div>

                <div className="card mb-8">
                    <VerifyForm />
                </div>

                <div className="space-y-6">
                    <h2 className="text-h3 text-white">How Verification Works</h2>

                    <div className="card space-y-4">
                        <div className="flex gap-4">
                            <FiCheckCircle className="w-5 h-5 text-success flex-shrink-0 mt-0.5" />
                            <div>
                                <h3 className="font-medium text-white mb-1">On-Chain Generation</h3>
                                <p className="text-sm text-gray-400">
                                    When a token is created, the ICP canister calls <code className="text-accent">raw_rand()</code>
                                    from the management canister. This generates 32 cryptographically secure bytes.
                                </p>
                            </div>
                        </div>

                        <div className="flex gap-4">
                            <FiCheckCircle className="w-5 h-5 text-success flex-shrink-0 mt-0.5" />
                            <div>
                                <h3 className="font-medium text-white mb-1">Immutable Storage</h3>
                                <p className="text-sm text-gray-400">
                                    The seed is stored directly in the canister's stable memory.
                                    It cannot be changed after creation.
                                </p>
                            </div>
                        </div>

                        <div className="flex gap-4">
                            <FiCheckCircle className="w-5 h-5 text-success flex-shrink-0 mt-0.5" />
                            <div>
                                <h3 className="font-medium text-white mb-1">Independent Verification</h3>
                                <p className="text-sm text-gray-400">
                                    You can query the canister directly or use the ICP dashboard to verify
                                    that the seed matches what was generated at creation time.
                                </p>
                            </div>
                        </div>
                    </div>

                    <div className="flex gap-4 p-4 bg-warning/5 border border-warning/10 rounded-card">
                        <FiAlertTriangle className="w-5 h-5 text-warning flex-shrink-0 mt-0.5" />
                        <div>
                            <h3 className="font-medium text-warning mb-1">Trust Verification</h3>
                            <p className="text-sm text-gray-400">
                                Don't trust — verify. The randomness is generated by ICP's threshold cryptography,
                                not by our servers. You can independently confirm this on-chain.
                            </p>
                        </div>
                    </div>

                    <div className="card">
                        <h3 className="font-medium text-white mb-4 flex items-center gap-2">
                            <FiInfo className="w-4 h-4 text-accent" />
                            Technical Details
                        </h3>
                        <div className="space-y-2 text-sm font-mono text-gray-400">
                            <p><span className="text-accent">Source:</span> IC Management Canister</p>
                            <p><span className="text-accent">Method:</span> raw_rand()</p>
                            <p><span className="text-accent">Output:</span> 32 bytes (256 bits)</p>
                            <p><span className="text-accent">Algorithm:</span> Threshold BLS signatures</p>
                            <p><span className="text-accent">Security:</span> 2/3 subnet consensus required</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
